CONFIG_BT_DEVICE_NAME="My Keyb"
CONFIG_BT_DEVICE_NAME_MAX=20

# Sleep after 30 mins (30*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_PM_SOFT_OFF=y

# MOUSE
CONFIG_ZMK_POINTING=y

# Enables a combination of settings that are planned to be default in future
# versions of ZMK to improve connection stability. This includes changes to
# timing on BLE pairing initiation, restores use of the updated/new LLCP
# implementation, and disables 2M PHY support.
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n

# Report type NKRO enabled
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8

# Diaplay config
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Report battery peripheral battery level
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

CONFIG_BT_BAS=n # prevent battery reporting waking up macOs

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10


# attempt to avoid freezing
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
